blueprints/post_blueprint.py
from datetime import date
from functools import wraps
from flask import Blueprint
from flask import render_template, redirect, url_for, flash, abort
from models.forms import CreatePostForm, CommentForm
from flask_login import current_user
from models.usermodel import db, BlogPost, Comment

post_blueprint = Blueprint('post_blueprint', __name__)

@post_blueprint.route('/')
def get_all_posts():
    posts = BlogPost.query.all()
    return render_template("index.html", all_posts=posts)


@post_blueprint.route('/example')
def index():
    return "This is an example app"


def admin_only(func):
    @wraps(func)
    def wrapper(*args, **kwargs):
        if current_user.id != 1:
            print('cannot add post! ', func)
            return abort(403)
        else:
            print('admin only: ', func)
            return func(*args, **kwargs)
    return wrapper

@post_blueprint.route("/new-post", methods=["GET", "POST"])
def add_new_post():
    form = CreatePostForm()
    print('add_new_post form: ', form)
    if form.validate_on_submit():
        new_post = BlogPost(
            title=form.title.data,
            subtitle=form.subtitle.data,
            body=form.body.data,
            img_url=form.img_url.data,
            author=current_user,
            date=date.today().strftime("%B %d, %Y")
        )
        print('new_post: ', new_post)
        db.session.add(new_post)
        db.session.commit()
        return redirect(url_for("post_blueprint.get_all_posts"))
    print('before make-post')
    return render_template("make-post.html", form=form)


@post_blueprint.route("/edit-post/<int:post_id>", methods=["GET", "POST"])
@admin_only
def edit_post(post_id):
    post = BlogPost.query.get(post_id)
    edit_form = CreatePostForm(
        title=post.title,
        subtitle=post.subtitle,
        img_url=post.img_url,
        author=post.author,
        body=post.body
    )
    if edit_form.validate_on_submit():
        post.title = edit_form.title.data
        post.subtitle = edit_form.subtitle.data
        post.img_url = edit_form.img_url.data
        post.author = edit_form.author.data
        post.body = edit_form.body.data
        db.session.commit()
        return redirect(url_for("show_post", post_id=post.id))

    return render_template("make-post.html", form=edit_form)


@post_blueprint.route("/delete/<int:post_id>")
def delete_post(post_id):
    post_to_delete = BlogPost.query.get(post_id)
    db.session.delete(post_to_delete)
    db.session.commit()
    return redirect(url_for('post_blueprint.get_all_posts'))


@post_blueprint.route("/post/<int:post_id>", methods=["GET", "POST"])
def show_post(post_id):
    form = CommentForm()
    requested_post = BlogPost.query.get(post_id)

    if form.validate_on_submit():
        if not current_user.is_authenticated:
            flash("need to login or register to comment")
            return redirect(url_for("login"))

        new_comment = Comment(
            text = form.comment_text.data,
            comment_author = current_user,
            parent_post = requested_post
        )
        print('new comment: ', new_comment)
        db.session.add(new_comment)
        db.session.commit()

    return render_template("post.html", post=requested_post, form=form, current_user=current_user)

blueprints/user_blueprint.py
# https://realpython.com/flask-blueprint/
from flask import Blueprint
from flask import render_template, request, redirect, url_for, flash
from models.forms import RegisterForm, LoginForm
from flask_login import login_user, logout_user
from models.usermodel import db, User
from werkzeug.security import generate_password_hash, check_password_hash

user_blueprint = Blueprint('user_blueprint', __name__)
@user_blueprint.route('/example')
def index():
    return "This is an example app"


@user_blueprint.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('post_blueprint.get_all_posts'))


@user_blueprint.route('/register', methods=["GET", "POST"])
def register():
    form = RegisterForm()
    print('def register email: ', request.form.get('email'))
    if User.query.filter_by(email=request.form.get('email') ).first():
        flash("您已經註冊過了，請登入。")
        print("您已經註冊過了，請登入。")
        return redirect(url_for('user_blueprint.login'))

    if form.validate_on_submit():
        hash_salt_password = generate_password_hash(
            form.password.data,
            method='pbkdf2:sha256',
            salt_length=8
        )
        new_user = User(
            email=form.email.data,
            name=form.name.data,
            password=hash_salt_password
        )

        db.session.add(new_user)
        db.session.commit()

        # this line will authenticate the user with Flask-login
        login_user(new_user)
        return redirect(url_for("post_blueprint.get_all_posts") )
    return render_template("register.html", form=form)


@user_blueprint.route('/login', methods=["GET", "POST"])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        email = form.email.data
        password = form.password.data

        user = User.query.filter_by(email=email).first()
        if user and check_password_hash(user.password, password):
            login_user(user)
            return redirect(url_for('post_blueprint.get_all_posts'))
        else:
            # sometimes we just don't want user to know, login or password which one is wrong.
            # if the user is a hacker.
            flash("wrong email or password! 請重新輸入。")
            return redirect(url_for('login'))

        # if not user:
        #     flash("That email does not exist, please try again.")
        #     return redirect(url_for('login'))
        # # Password incorrect
        # elif not check_password_hash(user.password, password):
        #     flash('Password incorrect, please try again.')
        #     return redirect(url_for('login'))
        # else:
        #     login_user(user)
        #     return redirect(url_for('post_blueprint.get_all_posts'))

    return render_template("login.html", form=form)

templates/about.html
{% include "header.html" %}

  <!-- Page Header -->
  <header class="masthead" style="background-image: url({{ url_for('static', filename='img/about-bg.jpg')}})">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="page-heading">
            <h1>About Me</h1>
            <span class="subheading">This is a site built using Flask framework + MySQL, hosting on AWS elastic beanstalk.</span>
            <span class="subheading">I coded along with an udemy 100 days of python course, then try to host it on AWS RDS MySQL instead of heroko + SQLite.</span>
          </div>
        </div>
      </div>
    </div>
  </header>

  <!-- Main Content -->
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
<!--        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Saepe nostrum ullam eveniet pariatur voluptates odit, fuga atque ea nobis sit soluta odio, adipisci quas excepturi maxime quae totam ducimus consectetur?</p>-->
<!--        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eius praesentium recusandae illo eaque architecto error, repellendus iusto reprehenderit, doloribus, minus sunt. Numquam at quae voluptatum in officia voluptas voluptatibus, minus!</p>-->
<!--        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Aut consequuntur magnam, excepturi aliquid ex itaque esse est vero natus quae optio aperiam soluta voluptatibus corporis atque iste neque sit tempora!</p>-->
      </div>
    </div>
  </div>

  <hr>

  {% include "footer.html" %}

templates/contact.html
{% include "header.html" %}

  <!-- Page Header -->
  <header class="masthead" style="background-image: url('{{ url_for('static', filename='img/contact-bg.jpg')}}')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="page-heading">
            <h1>Contact Me</h1>
            <span class="subheading">Have questions? I have answers.</span>
          </div>
        </div>
      </div>
    </div>
  </header>

  <!-- Main Content -->
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <p>Want to get in touch? Fill out the form below to send me a message and I will get back to you as soon as possible!</p>
        <!-- Contact Form - Enter your email address on line 19 of the mail/contact_me.php file to make this form work. -->
        <!-- WARNING: Some web hosts do not allow emails to be sent through forms to common mail hosts like Gmail or Yahoo. It's recommended that you use a private domain email address! -->
        <!-- To use the contact form, your site must be on a live web host with PHP! The form will not work locally! -->
        <form name="sentMessage" id="contactForm" novalidate>
          <div class="control-group">
            <div class="form-group floating-label-form-group controls">
              <label>Name</label>
              <input type="text" class="form-control" placeholder="Name" id="name" required data-validation-required-message="Please enter your name.">
              <p class="help-block text-danger"></p>
            </div>
          </div>
          <div class="control-group">
            <div class="form-group floating-label-form-group controls">
              <label>Email Address</label>
              <input type="email" class="form-control" placeholder="Email Address" id="email" required data-validation-required-message="Please enter your email address.">
              <p class="help-block text-danger"></p>
            </div>
          </div>
          <div class="control-group">
            <div class="form-group col-xs-12 floating-label-form-group controls">
              <label>Phone Number</label>
              <input type="tel" class="form-control" placeholder="Phone Number" id="phone" required data-validation-required-message="Please enter your phone number.">
              <p class="help-block text-danger"></p>
            </div>
          </div>
          <div class="control-group">
            <div class="form-group floating-label-form-group controls">
              <label>Message</label>
              <textarea rows="5" class="form-control" placeholder="Message" id="message" required data-validation-required-message="Please enter a message."></textarea>
              <p class="help-block text-danger"></p>
            </div>
          </div>
          <br>
          <div id="success"></div>
          <button type="submit" class="btn btn-primary" id="sendMessageButton">Send</button>
        </form>
      </div>
    </div>
  </div>

  <hr>

  {% include "footer.html" %}

templates/footer.html
<!-- Footer -->
<footer>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <ul class="list-inline text-center">
          <li class="list-inline-item">
            <a href="https://linkedin.com/in/sunpochin">
              <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-linkedin-in fa-stack-1x fa-inverse"></i>
                </span>
            </a>
          </li>
          <li class="list-inline-item">
            <a href="https://github.com/sunpochin/py_flask_blog">
              <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                </span>
            </a>
          </li>
        </ul>
        <p class="copyright text-muted"> Copyright &copy; <a href="https://www.linkedin.com/in/sunpochin">sunpochin</a> </p>
      </div>
    </div>
  </div>
</footer>

<!-- Bootstrap core JavaScript -->
<script src="{{ url_for('static', filename='vendor/jquery/jquery.min.js')}}"></script>
<script src="{{ url_for('static', filename='vendor/bootstrap/js/bootstrap.bundle.min.js')}}"></script>

<!-- Custom scripts for this template -->
<script src="{{ url_for('static', filename='js/clean-blog.min.js')}}"></script>

</body>

</html>

templates/header.html
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Pochin's Flask MySQL AWS site</title>

  <!-- Bootstrap core CSS -->
  <link href="{{ url_for('static', filename='vendor/bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">

  <!-- Custom fonts for this template -->
  <link href="{{ url_for('static', filename='vendor/fontawesome-free/css/all.min.css')}}" rel="stylesheet" type="text/css">
  <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

  <!-- Custom styles for this template -->
  <link href="{{ url_for('static', filename='css/clean-blog.min.css')}}" rel="stylesheet">

</head>

<body>

  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
    <div class="container">
      <a class="navbar-brand" href="{{url_for('post_blueprint.get_all_posts')}}">Pochin's Flask MySQL AWS site</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        Menu
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('post_blueprint.get_all_posts') }}">Home</a>
          </li>
          {% if current_user and current_user.is_authenticated: %}
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('user_blueprint.logout') }}">Log Out</a>
          </li>
          {% else: %}
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('user_blueprint.login') }}">Login</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('user_blueprint.register') }}">Register</a>
          </li>
          {% endif %}

          <li class="nav-item">
            <a class="nav-link" href="{{ url_for('about') }}">About</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

templates/index.html
{% include "header.html" %}

  <!-- Page Header -->
  <header class="masthead" style="background-image: url('https://images.unsplash.com/photo-1470092306007-055b6797ca72?ixlib=rb-1.2.1&auto=format&fit=crop&w=668&q=80')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="site-heading">
            <span class="subheading">My attempt trying to fit in some web developing interviews.</span>
            <span class="subheading">And, on this site you really can register and add new post and new comments !</span>

          </div>
        </div>
      </div>
    </div>
  </header>

  <!-- Main Content -->
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        {% for post in all_posts %}
        <div class="post-preview">
          <a href="{{ url_for('post_blueprint.show_post', post_id=post.id) }}">
            <h2 class="post-title">
              {{post.title}}
            </h2>
            <h3 class="post-subtitle">
              {{post.subtitle}}
            </h3>
          </a>
          <p class="post-meta">Posted by
            <a href="#">{{post.author.name}}</a>
            on {{post.date}}
          
            {% if current_user.id == 1: %}
            <a href="{{url_for('post_blueprint.delete_post', post_id=post.id) }}">✘</a>
            {% endif %}
          
          </p>
        </div>
        <hr>
        {% endfor %}


        <!-- New Post -->
        <div class="clearfix">
          <a class="btn btn-primary float-right" href="{{url_for('post_blueprint.add_new_post')}}">Create New Post</a>
        </div>
      </div>
    </div>
  </div>
  <hr>

{% include "footer.html" %}

templates/login.html
{% extends 'bootstrap/base.html' %}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}
{% include "header.html" %}

  <!-- Page Header -->
  <header class="masthead" style="background-image: url('https://images.unsplash.com/photo-1484100356142-db6ab6244067?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=80')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="page-heading">
            <h1>Log In</h1>
            <span class="subheading">Welcome Back!</span>
          </div>
        </div>
      </div>
    </div>
  </header>

  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto content">
        {% with messages = get_flashed_messages() %}
            {% if messages %}
                {% for mes in messages %}
                  <p>{{ mes }}</p>
                  <div class="alert alert-warning alert-dismissible" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        {{ mes }}
                    </div>
              {% endfor %}
            {% endif %}
        {% endwith %}
        {{ wtf.quick_form(form, novalidate=True, button_map={"submit": "primary"}) }}
      </div>
    </div>
  </div>


{% include "footer.html" %}
{% endblock %}

templates/make-post.html
{% extends 'bootstrap/base.html' %}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}
{% include "header.html" %}
  <!-- Page Header -->
  <header class="masthead" style="background-image: url('{{ url_for('static', filename='img/edit-bg.jpg')}}')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="page-heading">
            {% if is_edit: %}
            <h1>Edit Post</h1>
            {% else: %}
            <h1>New Post</h1>
            {% endif %}
            <span class="subheading">You're going to make a great blog post!</span>
          </div>
        </div>
      </div>
    </div>
  </header>

  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        {{ ckeditor.load() }}
        {{ ckeditor.config(name='body') }}
        {{ wtf.quick_form(form, novalidate=True, button_map={"submit": "primary"}) }}
      </div>
    </div>
  </div>

{% include "footer.html" %}
{% endblock %}

templates/post.html
{% include "header.html" %}
{% import "bootstrap/wtf.html" as wtf %}

  <!-- Page Header -->
  <header class="masthead" style="background-image: url('{{post.img_url}}')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="post-heading">
            <h1>{{post.title}}</h1>
            <h2 class="subheading">{{post.subtitle}}</h2>
            <span class="meta">Posted by
              <a href="#">{{post.author.name}}</a>
              on {{post.date}}</span>
          </div>
        </div>
      </div>
    </div>
  </header>

  <!-- Post Content -->
  <article>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
            {{ post.body|safe }}
          <hr>

            <div class="clearfix">
            <a class="btn btn-primary float-right" href="{{url_for('post_blueprint.edit_post', post_id=post.id)}}">Edit Post</a>
            </div>



<!--           Comments Area -->
                      {{ ckeditor.load() }}
                      {{ ckeditor.config(name='full') }}
<!--          #Configure it with the name of the form field from CommentForm-->
<!--          #Create the wtf quickform from CommentForm-->
                      {{ wtf.quick_form(form, novalidate=True, button_map={"submit": "primary"}) }}
          <div class="col-lg-8 col-md-10 mx-auto comment">
            {% for comment in post.comments %}
              <ul class="commentList">
                <li>
                    <div class="commenterImage">
                      <img src="{{ comment.comment_author.email | gravatar }}"/>
                    </div>
                    <div class="commentText">
                      {{comment.text|safe}}
                      <span class="date sub-text">{{comment.comment_author.name}}</span>
                    </div>
<!--                    <div class="commentText">-->
<!--                      <p>Some comment</p>-->
<!--                      <span class="date sub-text">comment author name</span>-->
<!--                    </div>-->
                </li>
              </ul>
            {% endfor %}
          </div>
        </div>
      </div>
    </div>
  </article>

  <hr>
{% include "footer.html" %}

templates/register.html
{% extends 'bootstrap/base.html' %}
{% import "bootstrap/wtf.html" as wtf %}

{% block content %}
{% include "header.html" %}

  <!-- Page Header -->
  <header class="masthead" style="background-image: url('https://images.unsplash.com/photo-1531592937781-344ad608fabf?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=800&q=80')">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">
          <div class="page-heading">
            <h1>Register</h1>
            <span class="subheading">Start Contributing to the Blog!</span>
          </div>
        </div>
      </div>
    </div>
  </header>

  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
       
       {{ wtf.quick_form(form, novalidate=True, button_map={"submit": "primary"}) }}

      </div>
    </div>
  </div>

{% include "footer.html" %}
{% endblock %}